import type { Article, ArticleReference } from "@/lib/articles";
import type { YouTubeVideo } from "@/lib/youtube";
import { chatCompletion } from "./openrouter";
import {
  obscureStoryPrompt,
  videoCompanionPrompt,
  WRITER_SYSTEM,
} from "./prompts";
import { stripAiPhrases } from "./sanitize";
import { validateReferences } from "./validate-story";

type StoryJson = {
  title: string;
  excerpt: string;
  category: string;
  content: string;
  references: ArticleReference[];
};

function slugify(title: string, suffix = ""): string {
  const base = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 55);
  return suffix ? `${base}-${suffix}` : base || "story";
}

function estimateReadMinutes(content: string): number {
  return Math.max(5, Math.ceil(content.split(/\s+/).length / 220));
}

function appendReferencesBlock(content: string, refs: ArticleReference[]): string {
  if (content.includes("## Sources")) return content;
  const block = refs
    .map((r, i) => {
      const year = r.year ? ` (${r.year})` : "";
      return `${i + 1}. ${r.title} — *${r.publisher}*${year}. [Link](${r.url})`;
    })
    .join("\n");
  return `${content.trim()}\n\n## Sources\n\n${block}`;
}

function parseStoryJson(raw: string): StoryJson {
  const cleaned = raw.replace(/^```json\s*/i, "").replace(/```\s*$/i, "").trim();
  const data = JSON.parse(cleaned) as StoryJson;
  data.title = stripAiPhrases(data.title);
  data.excerpt = stripAiPhrases(data.excerpt);
  data.content = stripAiPhrases(data.content);
  data.references = (data.references ?? []).map((r) => ({
    ...r,
    title: stripAiPhrases(r.title),
    publisher: stripAiPhrases(r.publisher ?? ""),
  }));
  return data;
}

async function generateStory(userPrompt: string, retries = 2): Promise<StoryJson> {
  let lastError = "unknown";

  for (let i = 0; i <= retries; i++) {
    const raw = await chatCompletion(
      [
        { role: "system", content: WRITER_SYSTEM },
        {
          role: "user",
          content:
            userPrompt +
            (i > 0
              ? "\n\nYour last draft failed validation: need 5+ real https references and 1400+ words. Fix and return JSON only."
              : ""),
        },
      ],
      { maxTokens: 8000, temperature: 0.35 + i * 0.05 }
    );

    try {
      const story = parseStoryJson(raw);
      const wordCount = story.content.split(/\s+/).length;
      const refCheck = validateReferences(story.references);
      if (!refCheck.ok) {
        lastError = refCheck.errors.join("; ");
        continue;
      }
      if (wordCount < 800) {
        lastError = "too short";
        continue;
      }
      story.content = appendReferencesBlock(story.content, story.references);
      return story;
    } catch (e) {
      lastError = e instanceof Error ? e.message : "parse error";
    }
  }

  throw new Error(`Story generation failed: ${lastError}`);
}

function toArticle(
  story: StoryJson,
  opts: {
    slugSuffix?: string;
    relatedVideoId?: string;
    sourceVideoId?: string;
  }
): Article {
  return {
    slug: slugify(story.title, opts.slugSuffix),
    title: story.title,
    excerpt: story.excerpt,
    readMinutes: estimateReadMinutes(story.content),
    category: story.category || "Weird America",
    content: story.content,
    references: story.references,
    relatedVideoId: opts.relatedVideoId ?? null,
    sourceVideoId: opts.sourceVideoId,
    autoGenerated: true,
  };
}

/** Template fallback when OpenRouter is not configured */
export function buildArticleFromVideoFallback(video: YouTubeVideo): Article {
  const content = `## ${video.title}\n\nWatch the documentary above for the full story. SeeStew covers this topic on [YouTube](https://www.youtube.com/@SeeStew).\n\n## Sources\n\n1. SeeStew — *YouTube*. [Link](https://www.youtube.com/@SeeStew)\n2. Library of Congress — *American History collections*. [Link](https://www.loc.gov/collections/)`;
  return {
    slug: slugify(video.title, video.id.slice(0, 6)),
    title: video.title,
    excerpt: video.description.slice(0, 160) || video.title,
    readMinutes: 3,
    category: "Documentary",
    content,
    references: [
      {
        title: "SeeStew YouTube Channel",
        publisher: "YouTube",
        url: "https://www.youtube.com/@SeeStew",
      },
      {
        title: "Library of Congress Digital Collections",
        publisher: "Library of Congress",
        url: "https://www.loc.gov/collections/",
      },
    ],
    relatedVideoId: video.id,
    sourceVideoId: video.id,
    autoGenerated: true,
  };
}

export async function buildArticleFromVideo(
  video: YouTubeVideo
): Promise<Article> {
  const story = await generateStory(videoCompanionPrompt(video));
  return toArticle(story, {
    slugSuffix: video.id.slice(0, 6),
    relatedVideoId: video.id,
    sourceVideoId: video.id,
  });
}

export async function buildObscureStory(
  usedTitles: string[],
  topicTitle?: string
): Promise<Article> {
  const prompt = topicTitle
    ? `Write the full article for this specific story: "${topicTitle}". ${obscureStoryPrompt(usedTitles)}`
    : obscureStoryPrompt(usedTitles);

  const story = await generateStory(prompt);
  return toArticle(story, {});
}
